name: firebase_setup
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  carousel_slider: ^4.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.0
  font_awesome_flutter: ^9.0.0
  http: ^0.13.3
  image_picker: ^0.8.0 
  firebase_storage: ^11.5.1
  charts_flutter: ^0.12.0
  shared_preferences: ^2.0.7
  sqflite: ^2.0.0+3





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder_image.jpg
    - assets/image2.jpeg
    - assets/image3.jpeg
    - assets/image1.jpeg
    - assets/images/ic_add_cart.png
    - assets/images/ic_discount.png
    - assets/images/promotion_one.png
    - assets/images/promotion_two.png
    - assets/images/promotion__one.png
    - assets/images/promotion_three.png
    - assets/images/ic_app_icon.png
    - assets/images/ic_category_image.png
    - assets/images/empty_shopping_cart_image.png
    - assets/images/empty_shopping_cart.png
    - assets/images/empty_wish_list.png
