// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW6vrUVC662pfDUJ3CleM3EhueyM1kjpU',
    appId: '1:302962007808:web:3818eee13b453aa2915de5',
    messagingSenderId: '302962007808',
    projectId: 'fire-base-test-2-c65e9',
    authDomain: 'fire-base-test-2-c65e9.firebaseapp.com',
    storageBucket: 'fire-base-test-2-c65e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC74DiNljgn2W6NBHxgUODh94KSpXEz1OI',
    appId: '1:302962007808:android:034aba99f6b910a3915de5',
    messagingSenderId: '302962007808',
    projectId: 'fire-base-test-2-c65e9',
    storageBucket: 'fire-base-test-2-c65e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjz_xUfFzK8DlVJUnYpanDv2s8AI9KhpQ',
    appId: '1:302962007808:ios:b5f410d55d342374915de5',
    messagingSenderId: '302962007808',
    projectId: 'fire-base-test-2-c65e9',
    storageBucket: 'fire-base-test-2-c65e9.appspot.com',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjz_xUfFzK8DlVJUnYpanDv2s8AI9KhpQ',
    appId: '1:302962007808:ios:be0965d2d44a3fc5915de5',
    messagingSenderId: '302962007808',
    projectId: 'fire-base-test-2-c65e9',
    storageBucket: 'fire-base-test-2-c65e9.appspot.com',
    iosBundleId: 'com.example.firebaseSetup.RunnerTests',
  );
}
